# Generated by Django 5.0.3 on 2024-03-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoapp', '0002_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='details_images/'),
        ),
    ]
